apiVersion: v1
kind: Service
metadata:
  labels:
    app: tls-proxy
    demo: roadshow
    repo: demo-apps
  name: tls-proxy-service
  namespace: frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http
  - port: 443
    protocol: TCP
    targetPort: 443
    name: tls
  selector:
    app: tls-proxy
  type: ClusterIP

