apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: frontend
  labels:
    app: wordpress-db
    demo: roadshow
    repo: demo-apps
spec:
  selector:
    app: wordpress-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      name: mysql
  type: ClusterIP

