# Service named "asset-cache-service"
# Listens on :8080
apiVersion: v1
kind: Service
metadata:
  labels:
    app: asset-cache
    demo: roadshow
    repo: demo-apps
  name: asset-cache-service
  namespace: frontend
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: asset-cache
  type: ClusterIP

