apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  namespace: grpc-c
  labels:
    app: emailservice
    demo: roadshow
    repo: demo-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: gcr.io/google-samples/microservices-demo/emailservice:v0.10.0
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          grpc:
            port: 8080
        livenessProbe:
          periodSeconds: 5
          grpc:
            port: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DISABLE_PROFILER
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
  namespace: grpc-c
  labels:
    app: emailservice
    demo: roadshow
    repo: demo-apps
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 8080
  selector:
    app: emailservice
