apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-cm
  namespace: backend
  labels:
    app: postgres
    demo: roadshow
    repo: demo-apps
rules:
- apiGroups: [""]       # core
  resources: ["configmaps"]
  verbs: ["get"]

