apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-atlas
  namespace: backend
  labels:
    app: backend-atlas
    demo: roadshow
    repo: demo-apps
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["*"]

