apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-atlas
  namespace: backend
  labels:
    app: backend-atlas
    demo: roadshow
    repo: demo-apps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backend-atlas
subjects:
  - kind: ServiceAccount
    name: backend-atlas
    namespace: backend

