# Service named "patient-db-service"
# Listens on :8080
apiVersion: v1
kind: Service
metadata:
  labels:
    app: patient-db
    demo: roadshow
    repo: demo-apps
  name: patient-db-service
  namespace: medical
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: tcp
  selector:
    app: patient-db
  type: ClusterIP

