apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres
  namespace: backend
  labels:
    app: postgres
    demo: roadshow
    repo: demo-apps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: postgres-cm
subjects:
  - kind: ServiceAccount
    name: postgres
    namespace: backend

