# Service named "postgres-service"
# Listens on :5432
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
    demo: roadshow
    repo: demo-apps
  name: postgres-service
  namespace: backend
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
    name: tcp
  selector:
    app: postgres
  type: ClusterIP

