# Service named "api-server-service"
# Listens on :9001
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-server
    demo: roadshow
    repo: demo-apps
  name: api-server-service
  namespace: backend
spec:
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 9001
    name: http
  selector:
    app: api-server
  type: ClusterIP

