# Service named "backend-atlas-service"
# Listens on :8080
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-atlas
    demo: roadshow
    repo: demo-apps
  name: backend-atlas-service
  namespace: backend
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: backend-atlas
  type: ClusterIP

