# Service named "varnish-service"
# Listens on :8080
apiVersion: v1
kind: Service
metadata:
  labels:
    app: varnish
    demo: roadshow
    repo: demo-apps
  name: varnish-service
  namespace: backend
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: varnish
  type: ClusterIP

