apiVersion: v1
kind: Namespace
metadata:
  name: patient-portal
  labels:
    app: patient-portal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database
    demo: roadshow
  name: database
  namespace: patient-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      securityContext:
        fsGroup: 0
      containers:
        - name: database
          image: quay.io/mfoster/patient-portal-database:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /pgdata
            - name: postgres-run
              mountPath: /var/run/postgresql
      volumes:
        - name: postgres-data
          emptyDir: {}
        - name: postgres-run
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: database
  name: database
  namespace: patient-portal
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: database
---