apiVersion: v1
kind: Service
metadata:
  labels:
    app: jump-host
    demo: roadshow
    repo: demo-apps
  name: jump-host-service
  namespace: operations
spec:
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 22
    name: tcp
  selector:
    app: jump-host
  type: ClusterIP

