apiVersion: v1
kind: Namespace
metadata:
  name: acs-fam-demo
  labels:
    demo: roadshow
    repo: demo-apps
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
    security.openshift.io/scc.podSecurityLabelSync: "false"
