# Service named "wordpress-service"
# Listens on :80
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
    demo: roadshow
    repo: demo-apps
  name: wordpress-service
  namespace: frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http
  selector:
    app: wordpress
  type: ClusterIP

