FROM registry.redhat.io/ubi9/openjdk-17-runtime:1.18-4
LABEL org.opencontainers.image.title="Demo Base: UBI9 OpenJDK 17"
LABEL org.opencontainers.image.version="1.0"
USER root
RUN microdnf install -y tar gzip && microdnf clean all
USER 185
