apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: payments-secrets
  namespace: payments
  labels:
    demo: roadshow
    repo: demo-apps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: payments-secrets
subjects:
- kind: User
  name: "joe@example.com"
  apiGroup: rbac.authorization.k8s.io

