apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: puppet-master
  namespace: operations
  labels:
    app: puppet-master
    demo: roadshow
    repo: demo-apps
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]

