# Service named "pupper-master-service"
# Listens on :8140
apiVersion: v1
kind: Service
metadata:
  labels:
    app: puppet-master
    demo: roadshow
    repo: demo-apps
  name: pupper-master-service
  namespace: operations
spec:
  ports:
  - port: 8140
    protocol: TCP
    targetPort: 8140
    name: http
  selector:
    app: puppet-master
  type: ClusterIP

