apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: payments-secrets
  namespace: payments
  labels:
    demo: roadshow
    repo: demo-apps
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]

