# Service named "mastercard-processor-service"
# Listens on :8080
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mastercard-processor
    demo: roadshow
    repo: demo-apps
  name: mastercard-processor-service
  namespace: payments
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: mastercard-processor
  type: ClusterIP

