apiVersion: v1
kind: ServiceAccount
metadata:
  name: visa-processor
  namespace: payments
  labels:
    app: visa-processor
    demo: roadshow
    repo: demo-apps
secrets:
- name: rhacs-demo-pull-pull-secret

