# Service named "gateway-service"
# Listens on :7777
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
    demo: roadshow
    repo: demo-apps
  name: gateway-service
  namespace: payments
spec:
  ports:
  - port: 7777
    protocol: TCP
    targetPort: 7777
    name: http
  selector:
    app: gateway
  type: ClusterIP

