apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  namespace: grpc-a
  labels:
    app: adservice
    demo: roadshow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
      - name: server
        image: gcr.io/google-samples/microservices-demo/adservice:v0.9.1
        ports:
        - containerPort: 9555
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: grpc-a
  labels:
    app: adservice
spec:
  type: ClusterIP
  ports:
  - port: 9555
    targetPort: 9555
  selector:
    app: adservice
