apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  namespace: grpc-a
  labels:
    app: currencyservice
    demo: roadshow
    repo: demo-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
        demo: roadshow
        repo: demo-apps
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: gcr.io/google-samples/microservices-demo/currencyservice:v0.10.0
        ports:
        - name: grpc
          containerPort: 7000
        readinessProbe:
          grpc:
            port: 7000
        livenessProbe:
          grpc:
            port: 7000
        env:
        - name: PORT
          value: "7000"
        - name: DISABLE_PROFILER
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  namespace: grpc-a
  labels:
    app: currencyservice
    demo: roadshow
    repo: demo-apps
spec:
  type: ClusterIP
  ports:
  - port: 7000
    targetPort: 7000
  selector:
    app: currencyservice
