apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  namespace: grpc-a
  labels:
    app: productcatalogservice
    demo: roadshow
    repo: demo-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
        demo: roadshow
        repo: demo-apps
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.10.0
        ports:
        - containerPort: 3550
        readinessProbe:
          grpc:
            port: 3550
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          grpc:
            port: 3550
          initialDelaySeconds: 15
          periodSeconds: 10
        env:
        - name: PORT
          value: "3550"
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  namespace: grpc-a
  labels:
    app: productcatalogservice
    demo: roadshow
    repo: demo-apps
spec:
  type: ClusterIP
  ports:
  - port: 3550
    targetPort: 3550
  selector:
    app: productcatalogservice
