apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
  namespace: grpc-a
  labels:
    app: recommendationservice
    demo: roadshow
    repo: demo-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
        demo: roadshow
        repo: demo-apps
    spec:
      containers:
      - name: server
        image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.10.0
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:3550"
---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  namespace: grpc-a
  labels:
    app: recommendationservice
    demo: roadshow
    repo: demo-apps
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: recommendationservice
