apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
  namespace: grpc-a
  labels:
    app: recommendationservice
    demo: roadshow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      containers:
      - name: server
        image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.9.1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  namespace: grpc-a
  labels:
    app: recommendationservice
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: recommendationservice
