apiVersion: v1
kind: Namespace
metadata:
  name: parasol-insurance
---
apiVersion: v1
kind: Service
metadata:
  name: parasol-insurance-service
  namespace: parasol-insurance
spec:
  selector:
    app: parasol-insurance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parasol-insurance
  namespace: parasol-insurance
  labels:
    app: parasol-insurance
    demo: roadshow
  annotations:
    app: parasol-insurance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parasol-insurance
  template:
    metadata:
      labels:
        app: parasol-insurance
    spec:
      containers:
      - name: parasol-insurance-container
        image: quay.io/jechoisec/ctf-web-to-system-01
        ports:
        - containerPort: 9090
        readinessProbe:
          httpGet:
            path: /
            port: 9090
          initialDelaySeconds: 10
          periodSeconds: 5
