apiVersion: v1
kind: Service
metadata:
  name: juice-shop
  namespace: juice-shop
  labels:
    demo: roadshow
    repo: demo-apps
spec:
  selector:
    app: juice-shop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP

